### ISSUE TITLE
NoClassDefFoundError with 1.4.2

### ISSUE THREAD

**Issue by konstantino** [eea/eea.elasticsearch.river.rdf#10]
Hi, 

I've been trying to use the plugin with elastic search 1.4.2 but I get an exception everytime I try to create a river. Here's the exception:

org.elasticsearch.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/elasticsearch/ElasticSearchIllegalArgumentException
	at org.elasticsearch.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at org.elasticsearch.common.cache.LocalCache.get(LocalCache.java:3937)
	at org.elasticsearch.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at org.elasticsearch.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.elasticsearch.common.inject.internal.FailableCache.get(FailableCache.java:51)
	at org.elasticsearch.common.inject.ConstructorInjectorStore.get(ConstructorInjectorStore.java:50)
	at org.elasticsearch.common.inject.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:50)
	at org.elasticsearch.common.inject.InjectorImpl.initializeBinding(InjectorImpl.java:372)
	at org.elasticsearch.common.inject.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:645)
	at org.elasticsearch.common.inject.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:580)
	at org.elasticsearch.common.inject.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:159)
	at org.elasticsearch.common.inject.InjectorImpl.getBindingOrThrow(InjectorImpl.java:119)
	at org.elasticsearch.common.inject.InjectorImpl.getInternalFactory(InjectorImpl.java:651)
	at org.elasticsearch.common.inject.FactoryProxy.notify(FactoryProxy.java:44)
	at org.elasticsearch.common.inject.BindingProcessor.runCreationListeners(BindingProcessor.java:210)
	at org.elasticsearch.common.inject.InjectorBuilder.initializeStatically(InjectorBuilder.java:130)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:102)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
	at org.elasticsearch.river.RiversService.createRiver(RiversService.java:140)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:275)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:269)
	at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/elasticsearch/ElasticSearchIllegalArgumentException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2585)
	at java.lang.Class.getDeclaredConstructors(Class.java:1906)
	at org.elasticsearch.common.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:177)
	at org.elasticsearch.common.inject.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:59)
	at org.elasticsearch.common.inject.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
	at org.elasticsearch.common.inject.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37)
	at org.elasticsearch.common.inject.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
	at org.elasticsearch.common.inject.internal.FailableCache$1.load(FailableCache.java:39)
	at org.elasticsearch.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at org.elasticsearch.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at org.elasticsearch.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at org.elasticsearch.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 25 more
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.ElasticSearchIllegalArgumentException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 38 more

**Comment by hemed** [comment]
I think I solved this before by replacing <code> org.elasticsearch.ElasticSearchIllegalArgumentException </code> with <code> java.lang.IllegalArgumentException</code> in the class <code>RDFRiver</code>

But now it has been fixed, so you can just download the latest rdf river plugin and it should be fine.

**Comment by konstantino** [comment]
thanks for the quick reply. just tried with 1.4.3 but the error is still there (same as before). I've also tried with 1.5.0 which I guess is still in an experimental mode but there are now issues there:

1) Error injecting constructor, java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
  at org.elasticsearch.river.eea_rdf.RDFRiver.<init>(Unknown Source)
  while locating org.elasticsearch.river.eea_rdf.RDFRiver
  while locating org.elasticsearch.river.River

**Comment by hemed** [comment]
So now it's another error -:)

The reason of this error is because you are passing a query as a String, don't do that, pass it as an array even if it has only one object.

More clearly,  don't do this:-
 <code> "query" : "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX cr: <http://cr.eionet.europa.eu/ontologies/contreg.rdf#> CONSTRUCT {?s ?p ?o} WHERE { ?s a cr:SparqlBookmark ; ?p ?o}" <code>

Instead, do this:-

 <code> "query" : [ "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX cr: <http://cr.eionet.europa.eu/ontologies/contreg.rdf#> CONSTRUCT {?s ?p ?o} WHERE { ?s a cr:SparqlBookmark ; ?p ?o}" ] <code>

**Comment by konstantino** [comment]
that worked better. thanks for the support!
